#!/bin/bash -e

if [[ ! -f CentOS-7-x86_64-GenericCloud-2111.qcow2c ]]; then
    echo "Downloading CentOS 7 image (first run only)"
    curl --remote-name https://cloud.centos.org/altarch/7/images/CentOS-7-x86_64-GenericCloud-2111.qcow2c
fi

cp CentOS-7-x86_64-GenericCloud-2111.qcow2c centos7.qcow2

virt-customize \
  -a centos7.qcow2 \
  --copy-in uncentos:/root \
  --password root:password:123456 \
  --install epel-release \
  --install sshfs \
  --append-line /root/mount:"sshfs -o StrictHostKeyChecking=no $USER@10.0.2.2:$PWD /mnt" \
  --chmod 0777:/root/mount \
  --ssh-inject root:file:"$HOME/.ssh/id_rsa.pub" \
  --selinux-relabel

qemu-img resize centos7.qcow2 +10G

